#!/bin/bash

fetch() {
  sp metadata | grep $1 | tr '|' '\n' | tail -n 1
}

G='\033[0;32m'
W='\033[1;37m'
NC='\033[0m'


artist=$(fetch "artist")
title=$(fetch "title")
album=$(fetch "album|")
lenght=$(fetch "length")
art=$(jp2a --colors --height=10 $(fetch "artUrl"))
meta=$(echo -e "
${G}Artist\t${NC}:\t${W}$artist
${G}Title\t${NC}:\t${W}$title
${G}Album\t${NC}:\t${W}$album
${G}Length\t${NC}:\t${W}$(($lenght / 1000000 / 60)) Minutes
")

paste <(printf "$art") <(printf "$meta")
